import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { NextIntlClientProvider } from "next-intl";
import MainLayout from "../components/layout/MainLayout";
import { AppProviders } from "./providers";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VPetId - Hồ sơ điện tử dành cho thú cưng của bạn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* Material Symbols không có sẵn trong next/font, giữ nguyên link như bản gốc */}
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-full flex flex-col">
        <Toaster
          position="top-right"
          reverseOrder={false}
        />
        <NextIntlClientProvider>
          <AppProviders>
            <MainLayout>
              {children}
            </MainLayout>
          </AppProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
